/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface Array_TestInterface extends utils.Interface {
  functions: {
    "testArr()": FunctionFragment;
    "viewArr()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "testArr" | "viewArr"): FunctionFragment;

  encodeFunctionData(functionFragment: "testArr", values?: undefined): string;
  encodeFunctionData(functionFragment: "viewArr", values?: undefined): string;

  decodeFunctionResult(functionFragment: "testArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewArr", data: BytesLike): Result;

  events: {};
}

export interface Array_Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Array_TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    testArr(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    viewArr(overrides?: CallOverrides): Promise<[BigNumber[]]>;
  };

  testArr(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  viewArr(overrides?: CallOverrides): Promise<BigNumber[]>;

  callStatic: {
    testArr(overrides?: CallOverrides): Promise<void>;

    viewArr(overrides?: CallOverrides): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    testArr(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    viewArr(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    testArr(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    viewArr(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
