/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  Array_Test,
  Array_TestInterface,
} from "../../../contracts/misc/Array_Test";

const _abi = [
  {
    inputs: [],
    name: "testArr",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "viewArr",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526040518060a00160405280600161ffff168152602001601461ffff168152602001601e61ffff16815260200161020161ffff16815260200161078361ffff16815250600090600561005692919061006f565b5061020160015534801561006957600080fd5b506100df565b8280548282559060005260206000209081019282156100b1579160200282015b828111156100b0578251829061ffff1690559160200191906001019061008f565b5b5090506100be91906100c2565b5090565b5b808211156100db5760008160009055506001016100c3565b5090565b61028a806100ee6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806380cc26381461003b578063f3790c5714610059575b600080fd5b610043610063565b60405161005091906101f3565b60405180910390f35b6100616100bb565b005b606060008054806020026020016040519081016040528092919081815260200182805480156100b157602002820191906000526020600020905b81548152602001906001019080831161009d575b5050505050905090565b600073__$7f37c9a29f30c6653170c3248a61374303$__6317dc59fa90916001546040518363ffffffff1660e01b81526004016100f992919061022b565b60006040518083038186803b15801561011157600080fd5b505af4158015610125573d6000803e3d6000fd5b50505050565b600081519050919050565b600082825260208201905092915050565b6000819050602082019050919050565b6000819050919050565b61016a81610157565b82525050565b600061017c8383610161565b60208301905092915050565b6000602082019050919050565b60006101a08261012b565b6101aa8185610136565b93506101b583610147565b8060005b838110156101e65781516101cd8882610170565b97506101d883610188565b9250506001810190506101b9565b5085935050505092915050565b6000602082019050818103600083015261020d8184610195565b905092915050565b8082525050565b61022581610157565b82525050565b60006040820190506102406000830185610215565b61024d602083018461021c565b939250505056fea26469706673582212204ff7cc4382d491a4b448f7c4b0f34a131ab40a68fc212a243100c1b0ca10705b64736f6c634300080b0033";

type Array_TestConstructorParams =
  | [linkLibraryAddresses: Array_TestLibraryAddresses, signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Array_TestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === "string" ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    "_isInterface" in xs[0]
  );
};

export class Array_Test__factory extends ContractFactory {
  constructor(...args: Array_TestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      const [linkLibraryAddresses, signer] = args;
      super(
        _abi,
        Array_Test__factory.linkBytecode(linkLibraryAddresses),
        signer
      );
    }
  }

  static linkBytecode(
    linkLibraryAddresses: Array_TestLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode;

    linkedBytecode = linkedBytecode.replace(
      new RegExp("__\\$7f37c9a29f30c6653170c3248a61374303\\$__", "g"),
      linkLibraryAddresses["contracts/libs/Array.sol:Array"]
        .replace(/^0x/, "")
        .toLowerCase()
    );

    return linkedBytecode;
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Array_Test> {
    return super.deploy(overrides || {}) as Promise<Array_Test>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Array_Test {
    return super.attach(address) as Array_Test;
  }
  override connect(signer: Signer): Array_Test__factory {
    return super.connect(signer) as Array_Test__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Array_TestInterface {
    return new utils.Interface(_abi) as Array_TestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Array_Test {
    return new Contract(address, _abi, signerOrProvider) as Array_Test;
  }
}

export interface Array_TestLibraryAddresses {
  ["contracts/libs/Array.sol:Array"]: string;
}
