name: main 

on:
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn 
      - run: yarn hardhat compile
